---
- hosts: liferay
  remote_user: root
  
  vars_files:
    - vars/main.yml

  roles:
# jboss standalone default
    - create-jboss-user
    - jdk-install
    - eap-install-dependencies
    - eap-install-standalone-from-jar
    - eap-standalone-service-configuration-rhel
    - eap-host-controller-configuration
    - eap-apply-patches
    - eap-host-firewalld
# liferay
    - liferay-dependencies
    - liferay-prep
    - liferay-datasource
    - liferay-deploy-war
